### ISSUE TITLE
Add dev command

### ISSUE THREAD

**Issue by kevinresol** [lix-pm/lix.client#10]
Just like what `haxelib dev` does

**Comment by fullofcaffeine** [comment]
+1 for this! As a reference, for others that might stumble upon this, the solution for now is to simply go to `haxe_libraries/`, find the `hxml` for the library you want to link to a dev directory, and change  the `-cp` argument there to the full local filesystem path of the library.

**Comment by kevinresol** [comment]
you can actually use relative path: `-cp ../tink_core/src`

**Comment by thomasuster** [comment]
If you use the CP work around don't you have to change it back to github SomeLib/master before check in? That seems a little clunky

**Comment by sh-dave** [comment]
Hm, come to think of it, i guess this is basically the same issue i opened in #5? What i actually want is just to point to some path in the current project to use as library. '-cp' only gets you so far, as it doesn't pick up extraParams.hxml, doesn't expose your current library as -D some_lib=version and whatnot.

**Comment by emugel** [comment]
That's the main thing missing in lix in my experience. 
That and maybe a `--verbose` option (especially when you begin with lix, it would help figuring out how things work, anyway it's out of topic).

**Comment by back2dos** [comment]
Not sure what to do about this. It would be trivial to add a dev command that does the very same change to the hxml, but when you mistakenly commit that, the problem is all the same. And if the info gets stored in some untracked place, then again, if you commit the state, it seems pretty likely it won't work anywhere else. Suggestions?

**Comment by benmerckx** [comment]
The reason you're editing the hxml file is because you're testing or introducing changes. That change will need to be pulled in after publishing. I think adding a dev command that points to a relative directory is exactly what we need but to be safer you could add a -cmd echo "Compiling with dev library: ..." or something to it so you're reminded.

**Comment by Gama11** [comment]
If there's a warning for dev versions of a library, what about dev versions of Haxe? (having a path in `.haxerc`)
