### ISSUE TITLE
Keep relative symlinks as is when untarring?

### ISSUE THREAD

**Issue by kevinresol** [lix-pm/lix.client#168]
In particular, I am interested in the rationale of the `Path.join` here:

https://github.com/lix-pm/lix.client/blob/c3211c70bc909a1503aa8b1c4064ada6c4a7f902/src/lix/client/Download.hx#L177

tracing back the history it was added in: https://github.com/lix-pm/switchx/commit/f56dadb6cbd9b7ec4b0a808fdedab4211435ea03

Because this is breaking CI caches where the cache folder paths can be different on different runners...

**Comment by back2dos** [comment]
I don't remember adding this to be honest, but I guess it fixed something for me while testing on WSL.

The main problem is that paths in the archives often require "peeling off" a level or two (because the actual files are nested in  `./wrapper1/wraper2/`). Doing this on a relative path is nonsense of course. 

I think I was assuming that the target path would somehow be a full path relative to the archive root, but in hindsight, that makes no sense. It seems far more likely that it's always a relative path (relative to the location of the symlink). I currently have no linux environment to confirm this, but if it is the case, then replacing `Path.join([Path.directory(path), entry.linkpath])` by just `entry.linkpath` should wind up linking to the correct file relatively.

**Comment by kevinresol** [comment]
> It seems far more likely that it's always a relative path (relative to the location of the symlink).

I think this is true. In particular, the tar file in concern here is the neko package, which looks like the following when uncompressed with a system unarchiver:

![Screenshot 2021-11-02 at 15 09 13](https://user-images.githubusercontent.com/1103788/139801360-bf48206e-2606-4c2f-9eb2-7f5947bddbfc.png)

In constrast, when untarred with switchx, it will look some like:
 `libneko.2.dylib -> /absolute/path/to/this/folder/libneko.2.3.1.dylib`

and will break when you move the entire folder to somewhere else.
