### ISSUE TITLE
Submodules are absent when downloading library from GitHub

### ISSUE THREAD

**Issue by Starmapo** [lix-pm/lix.client#188]
Example: after using `lix install gh:Aidan63/linc_discord-rpc` ([repository](https://github.com/Aidan63/linc_discord-rpc)), the submodules aren't downloaded and the "lib" folder is completely absent. This prevents the project from being compiled.

I'm using Node.js v16.20.2 and lix v15.12.0.

**Comment by back2dos** [comment]
For github, lix uses the archives, primarily because of speed, but also because the archive CDN experiences far less outages than the rest of the github infrastructure.

Unfortunately, the archive does not contain submodules: https://github.com/dear-github/dear-github/issues/214

I'm inclined to suggest Aidan63/linc_discord-rpc as a submodule to your project for the time being ;)

**Comment by kevinresol** [comment]
iirc u can use the git: protocol instead of gh:
That should support submodules

**Comment by Starmapo** [comment]
> iirc u can use the git: protocol instead of gh: That should support submodules

It worked! I was kinda confused by the `git:` syntax in the README file, but this got the job done:

`lix install git:https://github.com/Aidan63/linc_discord-rpc`

This was the only thing stopping me from using lix, so thank you very much :)
